saltdash/dash/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from . import views

app_name = "dash"

urlpatterns = [
    # placeholder for dashboard
    path("", RedirectView.as_view(url=reverse_lazy("dash:job_list"))),
    path("get-started/", views.get_started, name="get_started"),
    path("job/", views.job_list, name="job_list"),
    path("job/<int:jid>/", views.job_detail, name="job_detail"),
    path(
        "job/<int:jid>/success/",
        views.job_detail,
        {"success": True},
        name="job_detail_success",
    ),
    path(
        "job/<int:jid>/failure/",
        views.job_detail,
        {"success": False},
        name="job_detail_failed",
    ),
    path("job/<int:jid>/<str:minion>/", views.result_detail, name="result_detail"),
    path("result/", views.result_list, name="result_list"),
]

saltdash/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("-/", include("django_alive.urls")),
    path("admin/", admin.site.urls),
    path(
        "{}/".format(settings.SOCIAL_AUTH_URL_PREFIX),
        include("social_django.urls", namespace="social"),
    ),
    path("", include("saltdash.dash.urls")),
]

saltdash/dash/models.py
import fnmatch
import json

from django.conf import settings
from django.contrib.postgres.fields import ArrayField, JSONField
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.functional import cached_property


class Job(models.Model):
    jid = models.CharField(verbose_name="job id", max_length=50, primary_key=True)
    load = JSONField()

    class Meta:
        db_table = "jids"
        ordering = ["-jid"]

    @cached_property
    def user(self):
        return self.load.get("user", None)

    @cached_property
    def args(self):
        return [a for a in self.load["arg"] if isinstance(a, str)]

    @cached_property
    def kwargs(self):
        for a in self.load["arg"]:
            if isinstance(a, dict) and a.get("__kwarg__"):
                del a["__kwarg__"]
                return a

    @property
    def saltreturn_set(self):
        # Fake foreign key relation
        return Result.objects.filter(jid=self.jid)

    @cached_property
    def successes(self):
        return self.saltreturn_set.successes().count()

    @cached_property
    def failures(self):
        return self.saltreturn_set.failures().count()

    @cached_property
    def completed(self):
        try:
            return self.saltreturn_set.all().order_by("-completed")[0].completed
        except IndexError:
            return None

    @property
    def targets(self) -> list:
        try:
            tgt = self.load["tgt"]
        except KeyError:
            tgt = self.load["id"]
        if (
            "tgt_type" in self.load
            and self.load["tgt_type"] == "list"
            and not isinstance(tgt, str)
        ):
            return tgt
        return [tgt]

    def __str__(self) -> str:
        fun = self.load["fun"]
        target_count = len(self.targets)
        if target_count > 10:
            targets = "{} targets".format(target_count)
        else:
            targets = ", ".join(self.targets)
        val = "{}: salt '{}' {}".format(self.jid, targets, fun)
        if self.user:
            val += " by {}".format(self.user)
        return val


class ResultQuerySet(models.QuerySet):
    def successes(self):
        return self.filter(
            Q(full_ret__contains={"retcode": 0})
            | Q(return_val__contains={"success": True})
        )

    def failures(self):
        return self.exclude(
            Q(full_ret__contains={"retcode": 0})
            | Q(return_val__contains={"success": True})
        )


class Result(models.Model):
    auto_id = models.AutoField(primary_key=True)
    minion = models.CharField(max_length=100, db_index=True, db_column="id")
    # This can't be a foreign key due to the order Salt might insert data into
    # the tables.
    jid = models.CharField(verbose_name="job id", max_length=50, db_index=True)
    fun = models.CharField("function", max_length=100)
    fun_args = ArrayField(
        models.CharField(max_length=255), verbose_name="function args", null=True
    )
    completed = models.DateTimeField(db_column="alter_time")
    full_ret = JSONField("full result")
    return_val = JSONField("result", db_column="return")
    success = models.BooleanField()

    objects = ResultQuerySet.as_manager()

    class Meta:
        db_table = "salt_returns"
        ordering = ["-completed"]

    def __str__(self):
        return "{}: {} on {}".format(self.jid, self.fun, self.minion)

    def get_absolute_url(self):
        return reverse("dash:result_detail", args=[self.jid, self.minion])

    @property
    def was_success(self):
        if "retcode" in self.full_ret:
            return self.full_ret["retcode"] == 0
        # Master results don't use retcode
        try:
            return self.return_val.get("success", False)
        except AttributeError:
            return False

    @cached_property
    def job(self) -> Job:
        try:
            return Job.objects.get(jid=self.jid)
        except Job.DoesNotExist:
            return Job(
                jid=self.full_ret["jid"],
                load={
                    "arg": self.full_ret.get("fun_args", []),
                    "fun": self.full_ret["fun"],
                    "jid": self.full_ret["jid"],
                    "tgt": [self.full_ret["id"]],
                    "user": self.full_ret["user"],
                    "tgt_type": "list",
                },
            )

    @cached_property
    def return_val_as_json(self) -> str:
        return json.dumps(self.return_val, indent=2)

    @property
    def result_type(self) -> str:
        for hidden in settings.HIDE_OUTPUT:
            if fnmatch.fnmatch(self.full_ret.get("fun", ""), hidden):
                return "hidden"
        if isinstance(self.return_val, dict):
            if self.return_val.get("fun") == "runner.state.orchestrate":
                return "orchestrate"
            try:
                list(self.return_val.values())[0]["__run_num__"]
                return "state"
            except (TypeError, IndexError, KeyError):
                return "json"
        return "text"

    @property
    def has_states(self) -> bool:
        return self.result_type in ["state", "orchestrate"]

    def states_with_status(self, status: str) -> int:
        return len([s for s in self.states if s["status"] == status])

    @cached_property
    def states_changed(self) -> int:
        return self.states_with_status("changed")

    @cached_property
    def states_failed(self) -> int:
        return self.states_with_status("failed")

    @cached_property
    def states_failed_requisite(self) -> int:
        return self.states_with_status("requisite-failed")

    @cached_property
    def states_unchanged(self) -> int:
        return self.states_with_status("unchanged")

    @cached_property
    def states(self) -> list:
        if self.result_type == "state":
            state_dict = self.return_val
        elif self.result_type == "orchestrate":
            state_dict = list(self.return_val["return"]["data"].values())[0]
        else:
            raise TypeError("Return must be for a state")
        sorted_run = sorted(state_dict.items(), key=lambda s: s[1]["__run_num__"])
        return [_convert_state(*args) for args in sorted_run]

    @cached_property
    def duration(self) -> float:
        return sum([s["duration"] for s in self.states])


def _convert_state(key: str, data: dict) -> dict:
    """Make state data more usable"""
    mod, id, name, fun = key.split("_|-")
    state = {
        "module": mod,
        "id": id,
        "function": fun,
        "name": name,
        "success": data["result"],
        "changed": bool(data["changes"]),
        "sls": data.get("__sls__"),
        "changes": data["changes"],
        "duration": data.get("duration", 0),
        "start_time": data.get("start_time"),
        "comment": data.get("comment", ""),
        "order": data["__run_num__"],
        "jid": data.get("__jid__"),
    }
    if not state["success"]:
        if state["comment"].startswith("One or more requisite failed:"):
            state["status"] = "requisite-failed"
        else:
            state["status"] = "failed"
    elif state["changed"]:
        state["status"] = "changed"
    else:
        state["status"] = "unchanged"
    return state

saltdash/dash/views.py
from django.conf import settings
from django.core.paginator import InvalidPage, Page, Paginator
from django.db.models import QuerySet
from django.http import (
    Http404,
    HttpRequest,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Job, Result

ITEMS_PER_PAGE = 25


def paginate_queryset(queryset: QuerySet, request: HttpRequest) -> dict:
    """Paginate the queryset, if needed."""
    paginator = Paginator(queryset, ITEMS_PER_PAGE)
    page = request.GET.get("page") or 1
    try:
        page_number = int(page)
    except ValueError:
        if page == "last":
            page_number = paginator.num_pages
        else:
            raise Http404("Page is not 'last', nor can it be converted to an int.")
    try:
        page = paginator.page(page_number)
        return {
            "paginator": paginator,
            "page_obj": page,
            "object_list": page.object_list,
            "is_paginated": page.has_other_pages(),
        }
    except InvalidPage as e:
        raise Http404(
            "Invalid page ({page_number}): {exp}".format(
                page_number=page_number, exp=str(e)
            )
        )


def get_started(request):
    template = "dash/get_started.html"
    print(settings.DATABASES["default"])
    context = {
        "host": settings.DATABASES["default"]["HOST"] or "localhost",
        "name": settings.DATABASES["default"]["NAME"],
        "port": settings.DATABASES["default"]["PORT"] or 5432,
        "user": settings.DATABASES["default"]["USER"] or None,
    }
    return render(request, template, context)


def job_list(request):
    template = "dash/job_list.html"
    qs = Job.objects.all()
    show_system = "system" in request.GET
    if not show_system:
        qs = qs.exclude(load__fun="saltutil.find_job")
    context = {"job_list": qs, "has_system_jobs": show_system}
    context.update(paginate_queryset(qs, request))
    return render(request, template, context)


def job_detail(request, jid, success=None):
    template = "dash/job_detail.html"
    job = get_object_or_404(Job, jid=jid)
    filters = {"jid": jid}
    if success is not None:
        filters["success"] = success
    qs = Result.objects.filter(**filters)
    count = qs.count()
    if count == 1:
        return HttpResponseRedirect(
            reverse(
                "dash:result_detail", kwargs={"jid": qs[0].jid, "minion": qs[0].minion}
            )
        )
    context = {"job": job, "result_list": qs}
    context.update(paginate_queryset(qs, request))
    return render(request, template, context)


def result_list(request):
    template = "dash/result_list.html"
    qs = Result.objects.all()
    filters = {}
    show_system = "system" in request.GET
    if not show_system:
        qs = qs.exclude(fun="saltutil.find_job")
    if "minion" in request.GET:
        filters["minion"] = request.GET["minion"]
    qs = qs.filter(**filters)
    context = {"result_list": qs, "filters": filters, "has_system_jobs": show_system}
    context.update(paginate_queryset(qs, request))
    return render(request, template, context)


def result_detail(request, jid, minion):
    template = "dash/result_detail.html"
    result = get_object_or_404(Result, jid=jid, minion=minion)
    context = {"job": result.job, "result": result}
    return render(request, template, context)

saltdash/templates/dash/_job_summary.html
<h3>
  <code>{{ job.load.fun }}</code>
  {% if job.user %}<small class="text-muted">by {{ job.user }}</small>{% endif %}
</h3>
<h6>Targets: <small class="text-muted">{{ job.targets|join:", " }}</small> </h6>


<h6>Args: {% if not job.load.arg %}<span class="text-muted">[]</span>{% endif %}</h6>
{% if job.args or job.kwargs %}
  <ul>
    {% for arg in job.args %}
      <li><code>{{ arg }}</code></li>
    {% endfor %}
    {% for k, v in job.kwargs.items %}
      <li><code>{{ k }}={{ v }}</code></li>
    {% endfor %}
  </ul>
{% endif %}

saltdash/templates/dash/_pagination.html
{% load dash_tags %}
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">&larr; Previous</a>
      </li>
    {% else %}
      <li class="page-item">
        <a class="page-link" href="#">&larr; Previous</a>
      </li>
    {% endif %}
    {% for pagenum in paginator.page_range|clipped_page_range:page_obj.number %}
      <li class="page-item{% if not pagenum %} disabled{% endif %}{% if page_obj.number == pagenum %} active{% endif %}">
        <a class="page-link" href="{% if pagenum %}?{% url_replace page=pagenum %}{% endif %}">{{ pagenum|default_if_none:"&hellip;" }}</a>
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">Next &rarr;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Next &rarr;</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

saltdash/templates/dash/_result_card.html
{% load dash_tags %}
<div class="card mb-4" id="{{ result.pk }}">
  <div class="card-body">
    <a href="{% url "dash:result_detail" jid=result.jid minion=result.minion  %}"
       class="float-right ml-1 badge badge-{% if result.was_success %}success{% else %}danger{% endif %}">
      {% if result.was_success %}√{% else %}x{% endif %}
    </a>
    {% if result.has_states %}
      <code class="float-right small text-muted">{{ result.duration|pretty_time }}</code>
    {% endif %}

    <h4 class="card-title">
      <code><a href="{% url "dash:result_detail" jid=result.jid minion=result.minion  %}">
        {{ result.minion }}
      </a></code>
    </h4>
    {% if show_job %}
    {% include "dash/_job_summary.html" with job=result.job %}
  {% endif %}

    {% if result.has_states %}
      {% if result.states_failed > 0 %}
        <a href="#"
           data-toggle="collapse-optimized"
           data-button-toggle-class="danger"
           data-target='div#result-{{ result.pk }}'
           data-target-status='failed'
           class="btn btn-sm btn-danger">{{ result.states_failed }} failed</a>
      {% endif %}

      {% if result.states_failed_requisite > 0 %}
        <a href="#"
           data-toggle="collapse-optimized"
           data-button-toggle-class="warning"
           data-target='div#result-{{ result.pk }}'
           data-target-status="requisite-failed"
           class="btn btn-sm btn-outline-warning">{{ result.states_failed_requisite }} failed req</a>
      {% endif %}

      {% if result.states_changed > 0 %}
        <a href="#"
           data-toggle="collapse-optimized"
           data-button-toggle-class="success"
           data-target='div#result-{{ result.pk }}'
           data-target-status="changed"
           class="btn btn-sm btn{% if collapsed %}-outline{% endif %}-success">{{ result.states_changed }} changed</a>
      {% endif %}

      {% if result.states_unchanged > 0 %}
        <a href="#"
           data-toggle="collapse-optimized"
           data-button-toggle-class="secondary"
           data-target='div#result-{{ result.pk }}'
           data-target-status='unchanged'
           class="btn btn-sm btn-outline-secondary">{{ result.states_unchanged }} unchanged</a>
      {% endif %}

      <div id="result-{{ result.pk }}" class="state-list-container state-failed{% if not collapsed %} state-changed{% endif %}">
        {% include "dash/_results/"|add:result.result_type|add:".html" with result=result %}
      </div>
    {% else %}

      {# not state output, just text/json #}
      {% if collapsed %}
      <a href="#result-{{ result.pk }}"
         data-toggle="collapse"
         class="text-muted{% if result.was_success %} collapsed{% endif %}">Show/hide results</a>
      {% endif %}
      {% if result.return_val %}
        <div id="result-{{ result.pk }}"
             class="collapse {% if not collapsed or not result.was_success %}show{% endif %}">
          {% include "dash/_results/"|add:result.result_type|add:".html" with result=result %}
        </div>
      {% endif %}
    {% endif %}
  </div>

  {% if result.completed %}
    <div class="card-footer text-muted">
      {{ result.completed }}
    </div>
  {% endif %}
</div>

saltdash/templates/dash/base.html
{% extends "base.html" %}

saltdash/templates/dash/get_started.html
{% extends "dash/base.html" %}
{% block title %}Get Started{% endblock %}

{% block container %}
  <div class="alert alert-danger" role="alert">
    Uh-oh... Looks like Salt hasn't reported any data to the database yet.
  </div>
  {% if host == '127.0.0.1' or host == 'localhost' %}
    <div class="alert alert-warning" role="alert">
      You're using a database on <code>localhost</code>. This will only work if the Salt Master
      on the same host.
    </div>
  {% endif %}
  {% if not user %}
    <div class="alert alert-warning" role="alert">
      You haven't set a user for your database, you'll need to add one in the settings below.
    </div>
  {% endif %}
  <h2>Be sure you've taken the following steps:</h2>
  <ol>
    <li>
      Create <code>/etc/salt/master.d/saltdash.conf</code> with the this content (be sure to set your actual password):
      <pre><code>
master_job_cache: pgjsonb
returner.pgjsonb.host: {{ host }}
returner.pgjsonb.pass: **********
returner.pgjsonb.db: {{ name }}
returner.pgjsonb.port: {{ port }}
returner.pgjsonb.user: {{ user|default_if_none:"????" }}
</code></pre>
    </li>
    <li>Restart the <code>salt-master</code> service</li>
    <li>Run a test command like <code>salt '*' test.ping</code></li>
  </ol>
{% endblock %}

saltdash/templates/dash/job_detail.html
{% extends "dash/base.html" %}
{% block title %}Jobs : {{ job.jid }}{% endblock %}
{% block nav-jobs-active %}active{% endblock %}
{% block breadcrumbs %}
  <a class="breadcrumb-item" href="{% url "dash:job_list" %}">Jobs</a>
  <span class="breadcrumb-item active">{{ job.jid }}</span>
{% endblock %}

{% block container %}
  <div class="alert alert-secondary" role="alert">
    {% include "dash/_job_summary.html" %}
  </div>

  {% for result in object_list %}
    {% include "dash/_result_card.html" with collapsed="true" %}
  {% endfor %}
  {% include "dash/_pagination.html" %}
{% endblock %}

saltdash/templates/dash/job_list.html
{% extends "dash/base.html" %}
{% block title %}Jobs{% endblock %}
{% block nav-jobs-active %}active{% endblock %}
{% block breadcrumbs %}
  <span class="breadcrumb-item active">Jobs</span>
{% endblock %}
{% block extra-nav %}
  {% if has_system_jobs %}
    <a class="btn btn-sm btn-outline-light" href="{% url "dash:job_list" %}">Hide system jobs</a>
  {% else %}
    <a class="btn btn-sm btn-outline-light" href="{% url "dash:job_list" %}?system">Show system jobs</a>
  {% endif %}
{% endblock %}

{% block container %}
  {% for job in object_list %}
    <div class="card mb-4" id="{{ job.jid }}">
      <div class="card-body">
        {% if job.successes > 0 %}
          <a href="{% url "dash:job_detail_success" jid=job.jid  %}" class="float-right badge badge-success" title="{{ job.successes }} minion{{ job.successes|pluralize }} succeeded">{{ job.successes }}</a>
        {% endif %}
        {% if job.failures > 0 %}
          <a href="{% url "dash:job_detail_failed" jid=job.jid  %}" class="float-right badge badge-danger" title="{{ job.failures }} minion{{ job.failures|pluralize }} failed">{{ job.failures }}</a>
        {% endif %}
        {% if job.successes == 0 and job.failures == 0 %}
          <a href="{% url "dash:job_detail" jid=job.jid  %}" class="float-right badge badge-light" title="pending">&hellip;</a>
        {% endif %}
        {% include "dash/_job_summary.html" %}
        <a href="{% url "dash:job_detail" jid=job.jid  %}" class="card-link">Results &rarr;</a>
      </div>
      {% if job.completed %}
        <div class="card-footer text-muted">
          {{ job.completed }}
        </div>
      {% endif %}
    </div>
  {% endfor %}
  {% include "dash/_pagination.html" %}
{% endblock %}

saltdash/templates/dash/result_detail.html
{% extends "dash/base.html" %}
{% block nav-results-active %}active{% endblock %}
{% block title %}Jobs : {{ job.jid }} : {{ result.minion }}{% endblock %}
{% block breadcrumbs %}
  <a class="breadcrumb-item" href="{% url "dash:job_list" %}">Jobs</a>
  <a class="breadcrumb-item" href="{% url "dash:job_detail" jid=job.jid %}">{{ job.jid }}</a>
  <span class="breadcrumb-item active">{{ result.minion }}</span>
{% endblock %}

{% block container %}
  <div class="alert alert-secondary" role="alert">
    {% include "dash/_job_summary.html" %}
  </div>
  {% include "dash/_result_card.html" %}
{% endblock %}

saltdash/templates/dash/result_list.html
{% extends "dash/base.html" %}
{% load dash_tags %}

{% block title %}Results{% endblock %}
{% block nav-results-active %}active{% endblock %}
{% block breadcrumbs %}
  <a class="breadcrumb-item active" href="{% url "dash:result_list" %}">Results</a>
  {% if "minion" in filters %}
    <span class="breadcrumb-item">{{ filters.minion }}</span>
  {% endif %}

{% endblock %}
{% block extra-nav %}
  {% if has_system_jobs %}
    <a class="btn btn-sm btn-outline-light mr-2" href="{% url "dash:result_list" %}">Hide system jobs</a>
  {% else %}
    <a class="btn btn-sm btn-outline-light mr-2" href="{% url "dash:result_list" %}?system">Show system jobs</a>
  {% endif %}
  <form class="form-inline mt-1 mb-1" method="get">
    <div class="input-group input-group-sm">
      <input id="minion-filter" class="form-control" name="minion" list="minions" placeholder="Filter by minion" aria-label="Filter by minion">
      <div class="input-group-append">
        <button class="btn btn-outline-light" type="submit">Filter</button>
      </div>
    </div>
  </form>
{% endblock %}

{% block container %}
  {% for result in object_list %}
    {% include "dash/_result_card.html" with collapsed="true" show_job="true" %}
  {% endfor %}
  {% include "dash/_pagination.html" %}
  {% get_minions as minions %}
  <datalist id="minions">
    {% for minion in minions %}
      <option value="{{ minion }}">
    {% endfor %}
  </datalist>
{% endblock %}